/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: SILVER KEY (https://sketchfab.com/silver_key_nerd)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/laptop-model-black-404bef9dab2e46f99ebd4c09ed664ee3
Title: Laptop Model (Black)
*/

import React, { useEffect, useRef  } from 'react'
import { useGLTF, useVideoTexture } from '@react-three/drei'
import { useGSAP } from '@gsap/react'
import gsap from 'gsap'


const Computer = (props) => {
    const group=useRef()
    const { nodes, materials } = useGLTF('/models/laptop.glb')

    const texture=useVideoTexture(props.texture ? props.texture : '/textures/project/project1.mp4')
    
        texture.repeat.set(1.5, 1);
        texture.center.set(0.5, 0.5);

    useGSAP(()=>{
        gsap.from(group.current.rotation, {
            y:Math.PI/2,
            duration:1,
            ease:'power3.out'
        })
    },[texture])

  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[0, 0.475, 0]} scale={0.41}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_8.geometry}
          material={materials['Material.007']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_9.geometry}
          material={materials['Material.044']}
        />
        <group
          position={[0.302, -0.039, -2.052]}
          rotation={[0, 0, -0.07]}
          scale={[0.075, 0.012, 0.075]}>
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_51.geometry}
            material={materials['Material.105']}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.Object_52.geometry}
            material={materials['Material.106']}
          />
        </group>
        <group position={[0.106, -0.047, 0]} rotation={[0, 0, 0.017]}>
          <group position={[-0.091, -0.001, 0]} rotation={[0, 0, 0.172]} scale={[0.744, 1.028, 1]}>
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_57.geometry}
              material={materials['Material.007']}
            />
            <mesh
              castShadow
              receiveShadow
              geometry={nodes.Object_58.geometry}
              material={materials['Material.099']}//tutaj
            >
                <meshBasicMaterial map={texture} />
            </mesh>
            <group
              position={[0.045, 0.04, 0]}
              rotation={[0, 0, -1.297]}
              scale={[0.035, 0.025, 0.034]}>
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_60.geometry}
                material={materials['Material.100']}
              />
              <mesh
                castShadow
                receiveShadow
                geometry={nodes.Object_61.geometry}
                material={materials['Material.101']}
              />
            </group>
          </group>
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_11.geometry}
          material={materials['Material.012']}
          position={[1.795, -0.216, 0.088]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.877]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_13.geometry}
          material={materials['Material.012']}
          position={[1.795, -0.216, 2.022]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.182]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_15.geometry}
          material={materials['Material.012']}
          position={[1.534, -0.19, -1.84]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.344]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_17.geometry}
          material={materials['Material.012']}
          position={[1.276, -0.164, 1.571]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_19.geometry}
          material={materials['Material.012']}
          position={[1.278, -0.165, 1.969]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.24]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_21.geometry}
          material={materials['Material.012']}
          position={[1.278, -0.165, -1.854]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.321]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_23.geometry}
          material={materials['Material.012']}
          position={[0.547, -0.091, 2.084]}
          rotation={[0, 0, -0.1]}
          scale={[0.068, 0.034, 0.125]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_25.geometry}
          material={materials['Material.012']}
          position={[1.799, -0.217, 1.686]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_27.geometry}
          material={materials['Material.012']}
          position={[1.799, -0.217, -0.939]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_29.geometry}
          material={materials['Material.012']}
          position={[1.795, -0.216, -2.049]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_31.geometry}
          material={materials['Material.012']}
          position={[1.734, -0.21, -1.772]}
          rotation={[0, 0, -0.1]}
          scale={[0.057, 0.034, 0.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_33.geometry}
          material={materials['Material.012']}
          position={[1.863, -0.223, -1.772]}
          rotation={[0, 0, -0.1]}
          scale={[0.057, 0.034, 0.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_35.geometry}
          material={materials['Material.012']}
          position={[1.535, -0.188, 1.892]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.317]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_37.geometry}
          material={materials['Material.012']}
          position={[1.534, -0.19, 1.422]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_39.geometry}
          material={materials['Material.012']}
          position={[1.022, -0.139, 1.639]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_41.geometry}
          material={materials['Material.012']}
          position={[1.021, -0.139, 1.999]}
          rotation={[0, 0, -0.1]}
          scale={[0.113, 0.034, 0.204]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_43.geometry}
          material={materials['Material.012']}
          position={[1.018, -0.139, -1.957]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.223]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_45.geometry}
          material={materials['Material.012']}
          position={[0.76, -0.113, 1.746]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.127]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_47.geometry}
          material={materials['Material.012']}
          position={[0.761, -0.113, 2.046]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.157]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_49.geometry}
          material={materials['Material.012']}
          position={[0.761, -0.113, -1.907]}
          rotation={[0, 0, -0.1]}
          scale={[0.12, 0.034, 0.274]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_54.geometry}
          material={materials['Material.111']}
          position={[0.162, -0.073, -2.283]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[-0.022, 0.015, 0.022]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_63.geometry}
          material={materials.material_0}
          position={[0.851, -0.084, -1.665]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_65.geometry}
          material={materials.material_0}
          position={[1.022, -0.102, -1.933]}
          rotation={[1.571, 1.454, -Math.PI / 2]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_67.geometry}
          material={materials.material_0}
          position={[1.351, -0.135, -1.93]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_69.geometry}
          material={materials.material_0}
          position={[1.569, -0.144, 2.106]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_71.geometry}
          material={materials.material_0}
          position={[1.58, -0.159, -1.937]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_73.geometry}
          material={materials.material_0}
          position={[1.827, -0.17, 2.166]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_75.geometry}
          material={materials.material_0}
          position={[1.827, -0.17, 1.745]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_77.geometry}
          material={materials.material_0}
          position={[1.827, -0.17, 1.465]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_79.geometry}
          material={materials.material_0}
          position={[1.827, -0.17, 1.189]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_81.geometry}
          material={materials.material_0}
          position={[1.827, -0.17, -0.873]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_83.geometry}
          material={materials.material_0}
          position={[1.827, -0.17, -1.164]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_85.geometry}
          material={materials.material_0}
          position={[1.827, -0.17, -1.437]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_87.geometry}
          material={materials.material_0}
          position={[1.89, -0.177, -1.754]}
          rotation={[1.571, 1.468, -1.571]}
          scale={[0.064, 0.064, 0.04]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_89.geometry}
          material={materials.material_0}
          position={[1.762, -0.163, -1.75]}
          rotation={[1.571, 1.468, -1.571]}
          scale={[0.098, 0.098, 0.061]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_91.geometry}
          material={materials.material_0}
          position={[1.827, -0.17, -2.07]}
          rotation={[1.571, 1.468, -1.571]}
          scale={[-0.069, 0.064, 0.064]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_93.geometry}
          material={materials.material_0}
          position={[1.569, -0.144, 1.449]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_95.geometry}
          material={materials.material_0}
          position={[1.569, -0.144, 1.146]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_97.geometry}
          material={materials.material_0}
          position={[1.569, -0.144, 0.852]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_99.geometry}
          material={materials.material_0}
          position={[1.569, -0.144, 0.567]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_101.geometry}
          material={materials.material_0}
          position={[1.569, -0.144, 0.271]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_103.geometry}
          material={materials.material_0}
          position={[1.569, -0.144, -0.016]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_105.geometry}
          material={materials.material_0}
          position={[1.569, -0.144, -0.302]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_107.geometry}
          material={materials.material_0}
          position={[1.569, -0.144, -0.594]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_109.geometry}
          material={materials.material_0}
          position={[1.569, -0.144, -0.888]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_111.geometry}
          material={materials.material_0}
          position={[1.569, -0.144, -1.193]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_113.geometry}
          material={materials.material_0}
          position={[1.309, -0.117, -1.04]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_115.geometry}
          material={materials.material_0}
          position={[1.309, -0.117, -0.736]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_117.geometry}
          material={materials.material_0}
          position={[1.309, -0.117, -0.442]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_119.geometry}
          material={materials.material_0}
          position={[1.309, -0.117, -0.173]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_121.geometry}
          material={materials.material_0}
          position={[1.309, -0.117, 0.136]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_123.geometry}
          material={materials.material_0}
          position={[1.309, -0.117, 0.423]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_125.geometry}
          material={materials.material_0}
          position={[1.309, -0.117, 0.72]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_127.geometry}
          material={materials.material_0}
          position={[1.309, -0.117, 1.004]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_129.geometry}
          material={materials.material_0}
          position={[1.309, -0.117, 1.299]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_131.geometry}
          material={materials.material_0}
          position={[1.309, -0.117, 1.601]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_133.geometry}
          material={materials.material_0}
          position={[1.309, -0.117, -1.337]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_135.geometry}
          material={materials.material_0}
          position={[1.053, -0.09, -1.264]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_137.geometry}
          material={materials.material_0}
          position={[1.053, -0.09, 1.659]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_139.geometry}
          material={materials.material_0}
          position={[1.053, -0.09, 1.364]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_141.geometry}
          material={materials.material_0}
          position={[1.053, -0.09, 1.064]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_143.geometry}
          material={materials.material_0}
          position={[1.053, -0.09, 0.78]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_145.geometry}
          material={materials.material_0}
          position={[1.053, -0.09, 0.496]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_147.geometry}
          material={materials.material_0}
          position={[1.053, -0.09, 0.193]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_149.geometry}
          material={materials.material_0}
          position={[1.053, -0.09, -0.094]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_151.geometry}
          material={materials.material_0}
          position={[1.053, -0.09, -0.4]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_153.geometry}
          material={materials.material_0}
          position={[1.053, -0.09, -0.672]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_155.geometry}
          material={materials.material_0}
          position={[1.053, -0.09, -0.979]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_157.geometry}
          material={materials.material_0}
          position={[1.053, -0.09, -1.563]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_159.geometry}
          material={materials.material_0}
          position={[0.739, -0.058, -1.154]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_161.geometry}
          material={materials.material_0}
          position={[0.792, -0.063, 1.758]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_163.geometry}
          material={materials.material_0}
          position={[0.792, -0.063, 1.456]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_165.geometry}
          material={materials.material_0}
          position={[0.792, -0.063, 1.172]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_167.geometry}
          material={materials.material_0}
          position={[0.792, -0.063, 0.876]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_169.geometry}
          material={materials.material_0}
          position={[0.792, -0.063, 0.601]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_171.geometry}
          material={materials.material_0}
          position={[0.792, -0.063, 0.309]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_173.geometry}
          material={materials.material_0}
          position={[0.792, -0.063, -0.003]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_175.geometry}
          material={materials.material_0}
          position={[0.792, -0.063, -0.285]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_177.geometry}
          material={materials.material_0}
          position={[0.792, -0.063, -0.579]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_179.geometry}
          material={materials.material_0}
          position={[0.792, -0.063, -0.865]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_181.geometry}
          material={materials.material_0}
          position={[0.752, -0.059, -1.455]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_183.geometry}
          material={materials.material_0}
          position={[1.316, -0.117, 2.116]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_185.geometry}
          material={materials.material_0}
          position={[1.054, -0.09, 2.121]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_187.geometry}
          material={materials.material_0}
          position={[0.755, -0.059, 2.121]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_189.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, 2.141]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_191.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, 1.838]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_193.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, 1.567]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_195.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, 1.012]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_197.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, 1.282]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_199.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, 0.182]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_201.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, -0.076]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_203.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, 0.467]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_205.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, 0.737]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_207.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, -0.882]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_209.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, -1.154]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_211.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, -0.609]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_213.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, -0.346]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_215.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, -1.424]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_217.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, -1.693]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Object_219.geometry}
          material={materials.material_0}
          position={[0.58, -0.041, -1.959]}
          rotation={[1.571, 1.468, -1.571]}
          scale={0.064}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/models/laptop.glb')

export default Computer
